### ISSUE TITLE
Archiving nodejs-ko (node's i18n process has changed)

### ISSUE THREAD

**Issue by obensource** [iojs/iojs-kr#1198]
Dear **nodejs-ko** team,

Thank you for being part of the Node.js community. 🙏

The i18n Working Group is currently in the process of archiving node's l10n repositories since we've moved all translation efforts to the Crowdin platform over the past few years. We're planning on archiving all l10n repositories that follow the previous method that was established during the io.js fork on **01-14-22**. I believe this repository meets that criteria, but if there is a reason to continue to maintain nodejs/nodejs-ko other than localizing Node.js into Korean (and you'd like to keep this repository open), please respond here on this issue so we can discuss it and understand how to best help you in your efforts.

In the meantime, we'd love to have you come over and be a part of the i18n WG at: https://github.com/nodejs/i18n#contributing

Please feel free to reach out to us there, or to me directly if you'd like to understand how to get involved with node's current localization efforts.

All the best,
–Ben (Node.js i18n Lead)

**Comment by taggon** [comment]
Hello @obensource! 👋 

Thanks for letting us know the plan. @nodejs/nodejs-ko has [own blog](https://nodejs.github.io/nodejs-ko/) to publish the Node.js official security/release notes translated in Korean. You will see how active we have contributed to the local community if you check [the issues list](https://github.com/nodejs/nodejs-ko/issues?q=is%3Aissue).

Though we started the discussion after we got the notice from you, we still need time to discuss whether we continue to run our own blog. Could we have one or two weeks more? I'll let you know once we reach out an agreement.

**Comment by nschonni** [comment]
I'm not sure if you can port the blog into https://github.com/nodejs/nodejs.org/tree/main/locale/ko. I don't think any of the other localizations currently do that, but I know that some have been updating the banner messages like https://github.com/nodejs/nodejs.org/pull/4363

**Comment by taggon** [comment]
Hi @obensource! Thanks for your patience.

After the discussion, the @nodejs/nodejs-ko members have reached out to the agreement on archiving this repository. We decided to stop running our own blog I mentioned above.

**Comment by nschonni** [comment]
@taggon did you want to try and port over the content and/or continue doing the blog translation on the nodejs.org repo?

**Comment by outsideris** [comment]
I don't think all nodejs-ko group continues doing translation on crowdin,  but individual member can do. 
As our understanding, no other group translate nodejs blog posts.

**Comment by outsideris** [comment]
@obensource @nschonni Any update? 
@Trott still [manages this repository](https://github.com/nodejs/nodejs-ko/pull/1205).

**Comment by Trott** [comment]
I'm going to archive this repository, as all activity has moved to Crowdin. If there are questions or concerns, please contact a TSC member on the OpenJS Slack or open an issue in the github.com/nodejs/admin/ repository. Thanks.
